import {
  Room,
  Guest,
  Sale,
  Expense,
  Debt,
  InventoryItem,
  ExtraServiceItem,
  ProfitGoal,
} from '../types';

export const INITIAL_ROOMS: Room[] = [
  {
    id: 'room-101',
    number: '101',
    category: 'Simple',
    pricePerNight: 45000,
    status: 'available',
    notes: 'Primer piso, cama plaza y media, vista al patio interior.',
  },
  {
    id: 'room-102',
    number: '102',
    category: 'Simple',
    pricePerNight: 45000,
    status: 'cleaning',
    notes: 'Limpieza profunda de salida.',
  },
  {
    id: 'room-201',
    number: '201',
    category: 'Doble',
    pricePerNight: 65000,
    status: 'occupied',
    currentGuestName: 'Carlos Mendoza',
    currentGuestRut: '14.892.310-7',
    currentGuestPhone: '+56 9 7654 3210',
    checkInDate: '2026-07-25',
    checkOutDate: '2026-07-28',
    notes: '2 Camas de 1.5 plazas, frigobar habilitado.',
  },
  {
    id: 'room-202',
    number: '202',
    category: 'Doble',
    pricePerNight: 65000,
    status: 'available',
    notes: 'Segundo piso, baño recién remodelado.',
  },
  {
    id: 'room-301',
    number: '301',
    category: 'Matrimonial',
    pricePerNight: 85000,
    status: 'occupied',
    currentGuestName: 'Valentina Silva',
    currentGuestRut: '17.521.804-K',
    currentGuestPhone: '+56 9 9123 4567',
    checkInDate: '2026-07-24',
    checkOutDate: '2026-07-27',
    notes: 'Cama King, incluye desayuno buffet.',
  },
  {
    id: 'room-302',
    number: '302',
    category: 'Matrimonial',
    pricePerNight: 85000,
    status: 'available',
    notes: 'Tercer piso, aire acondicionado silenciador.',
  },
  {
    id: 'room-401',
    number: '401',
    category: 'Suite',
    pricePerNight: 140000,
    status: 'occupied',
    currentGuestName: 'Francisco Morales',
    currentGuestRut: '12.441.980-2',
    currentGuestPhone: '+56 9 8765 4321',
    checkInDate: '2026-07-22',
    checkOutDate: '2026-07-29',
    notes: 'Suite Ejecutiva, jacuzzi, terraza privada.',
  },
  {
    id: 'room-402',
    number: '402',
    category: 'Suite',
    pricePerNight: 140000,
    status: 'available',
    notes: 'Suite De Lujo Vista Panorámica.',
  },
];

export const INITIAL_GUESTS: Guest[] = [
  {
    id: 'guest-1',
    rut: '12.441.980-2',
    firstName: 'Francisco',
    lastName: 'Morales',
    email: 'f.morales@empresa.cl',
    phone: '+56 9 8765 4321',
    totalVisits: 5,
    totalSpent: 1480000,
    isFrequent: true,
    notes: 'Cliente corporativo vip. Prefiere Suite 401.',
    createdAt: '2025-11-10',
  },
  {
    id: 'guest-2',
    rut: '17.521.804-K',
    firstName: 'Valentina',
    lastName: 'Silva',
    email: 'valentina.silva@gmail.com',
    phone: '+56 9 9123 4567',
    totalVisits: 3,
    totalSpent: 680000,
    isFrequent: true,
    notes: 'Suele solicitar servicio de lavandería express.',
    createdAt: '2026-01-15',
  },
  {
    id: 'guest-3',
    rut: '14.892.310-7',
    firstName: 'Carlos',
    lastName: 'Mendoza',
    email: 'carlos.mendoza@latam.cl',
    phone: '+56 9 7654 3210',
    totalVisits: 1,
    totalSpent: 195000,
    isFrequent: false,
    notes: 'Viaje de negocios.',
    createdAt: '2026-07-25',
  },
  {
    id: 'guest-4',
    rut: '18.302.119-4',
    firstName: 'Andrea',
    lastName: 'Paredes',
    email: 'andrea.paredes@hotmail.com',
    phone: '+56 9 5544 3322',
    totalVisits: 2,
    totalSpent: 340000,
    isFrequent: true,
    notes: 'Turista recurrente.',
    createdAt: '2026-03-02',
  },
];

export const EXTRA_SERVICES_CATALOG: ExtraServiceItem[] = [
  { id: 'srv-1', name: 'Consumo Minibar (Bebida/Cerveza/Snack)', category: 'minibar', unitPrice: 5000 },
  { id: 'srv-2', name: 'Servicio de Lavandería (Kilo)', category: 'lavanderia', unitPrice: 8000 },
  { id: 'srv-3', name: 'Desayuno Buffet Adicional', category: 'cafeteria', unitPrice: 10000 },
  { id: 'srv-4', name: 'Estacionamiento Privado (Día)', category: 'estacionamiento', unitPrice: 6000 },
  { id: 'srv-5', name: 'Late Check-out (Hasta las 16:00)', category: 'late_checkout', unitPrice: 20000 },
  { id: 'srv-6', name: 'Tabla de Quesos y Vino Bienvenida', category: 'cafeteria', unitPrice: 25000 },
];

export const INITIAL_SALES: Sale[] = [
  {
    id: 'sale-1001',
    saleCode: 'VEN-2026-001',
    guestId: 'guest-1',
    guestRut: '12.441.980-2',
    guestName: 'Francisco Morales',
    guestEmail: 'f.morales@empresa.cl',
    guestPhone: '+56 9 8765 4321',
    vehiclePlate: 'KLPW-48',
    invoiceNumber: 'BOL-10492',
    isFrequentGuest: true,
    roomId: 'room-401',
    roomNumber: '401',
    roomCategory: 'Suite',
    checkInDate: '2026-07-22',
    checkOutDate: '2026-07-29',
    nightsCount: 7,
    roomTotal: 980000,
    extraServices: [
      { serviceId: 'srv-1', name: 'Consumo Minibar (Bebida/Cerveza/Snack)', unitPrice: 5000, quantity: 4 },
      { serviceId: 'srv-2', name: 'Servicio de Lavandería (Kilo)', unitPrice: 8000, quantity: 3 },
      { serviceId: 'srv-6', name: 'Tabla de Quesos y Vino Bienvenida', unitPrice: 25000, quantity: 1 },
    ],
    grandTotal: 1049000,
    paymentMethod: 'transferencia',
    paymentStatus: 'paid',
    createdAt: '2026-07-22T14:30:00Z',
    notes: 'Pago recibido por transferencia bancaria.',
  },
  {
    id: 'sale-1002',
    saleCode: 'VEN-2026-002',
    guestId: 'guest-2',
    guestRut: '17.521.804-K',
    guestName: 'Valentina Silva',
    guestEmail: 'valentina.silva@gmail.com',
    guestPhone: '+56 9 9123 4567',
    vehiclePlate: 'RSTX-12',
    invoiceNumber: 'BOL-10493',
    isFrequentGuest: true,
    roomId: 'room-301',
    roomNumber: '301',
    roomCategory: 'Matrimonial',
    checkInDate: '2026-07-24',
    checkOutDate: '2026-07-27',
    nightsCount: 3,
    roomTotal: 255000,
    extraServices: [
      { serviceId: 'srv-3', name: 'Desayuno Buffet Adicional', unitPrice: 10000, quantity: 2 },
    ],
    grandTotal: 275000,
    paymentMethod: 'debito',
    paymentStatus: 'paid',
    createdAt: '2026-07-24T12:15:00Z',
    notes: 'Pago Transbank Débito.',
  },
  {
    id: 'sale-1003',
    saleCode: 'VEN-2026-003',
    guestId: 'guest-3',
    guestRut: '14.892.310-7',
    guestName: 'Carlos Mendoza',
    guestEmail: 'carlos.mendoza@latam.cl',
    guestPhone: '+56 9 7654 3210',
    vehiclePlate: 'BHJY-90',
    invoiceNumber: 'FAC-00812',
    isFrequentGuest: false,
    roomId: 'room-201',
    roomNumber: '201',
    roomCategory: 'Doble',
    checkInDate: '2026-07-25',
    checkOutDate: '2026-07-28',
    nightsCount: 3,
    roomTotal: 195000,
    extraServices: [
      { serviceId: 'srv-1', name: 'Consumo Minibar (Bebida/Cerveza/Snack)', unitPrice: 5000, quantity: 2 },
    ],
    grandTotal: 205000,
    paymentMethod: 'efectivo',
    paymentStatus: 'partially_paid',
    pendingAmount: 35000,
    createdAt: '2026-07-25T16:00:00Z',
    notes: 'Anticipo $170.000 pagado en efectivo. Pendiente $35.000.',
  },
  {
    id: 'sale-1000',
    saleCode: 'VEN-2026-000',
    guestId: 'guest-4',
    guestRut: '18.302.119-4',
    guestName: 'Andrea Paredes',
    guestEmail: 'andrea.paredes@hotmail.com',
    guestPhone: '+56 9 5544 3322',
    isFrequentGuest: true,
    roomId: 'room-202',
    roomNumber: '202',
    roomCategory: 'Doble',
    checkInDate: '2026-07-10',
    checkOutDate: '2026-07-14',
    nightsCount: 4,
    roomTotal: 260000,
    extraServices: [],
    grandTotal: 260000,
    paymentMethod: 'tarjeta',
    paymentStatus: 'paid',
    createdAt: '2026-07-10T11:00:00Z',
    notes: 'Reserva previa.',
  }
];

export const INITIAL_EXPENSES: Expense[] = [
  // PRIORITY: Arriendo del local
  {
    id: 'exp-1',
    title: 'Arriendo del Local Hotel Colonos',
    category: 'fixed',
    subcategory: 'arriendo',
    amount: 3800000,
    vendor: 'Inmobiliaria Los Colonos SpA',
    expenseDate: '2026-07-05',
    status: 'paid',
    notes: '¡Prioridad crítica de costo fijo mensual!',
    createdAt: '2026-07-05T09:00:00Z',
  },
  {
    id: 'exp-2',
    title: 'Nómina de Sueldos y Imposiciones Personal',
    category: 'fixed',
    subcategory: 'sueldos',
    amount: 4200000,
    vendor: 'Sueldos Colaboradores Hotel',
    expenseDate: '2026-07-01',
    status: 'paid',
    notes: 'Sueldos recepción, camareras y mantenimiento.',
    createdAt: '2026-07-01T10:00:00Z',
  },
  {
    id: 'exp-3',
    title: 'Suministro Eléctrico Enel',
    category: 'fixed',
    subcategory: 'luz',
    amount: 480000,
    vendor: 'Enel Distribución Chile',
    expenseDate: '2026-07-15',
    status: 'paid',
    notes: 'Consumo mensual de climatización y alumbrado.',
    createdAt: '2026-07-15T11:00:00Z',
  },
  {
    id: 'exp-4',
    title: 'Agua Potable y Alcantarillado',
    category: 'fixed',
    subcategory: 'agua',
    amount: 210000,
    vendor: 'Aguas Andinas S.A.',
    expenseDate: '2026-07-18',
    status: 'paid',
    notes: 'Factura mensual lavandería y habitaciones.',
    createdAt: '2026-07-18T14:00:00Z',
  },
  {
    id: 'exp-5',
    title: 'Internet Fibra Óptica Dedicada + Cable TV',
    category: 'fixed',
    subcategory: 'internet',
    amount: 125000,
    vendor: 'Movistar Empresas',
    expenseDate: '2026-07-10',
    status: 'paid',
    notes: 'Plan 1Gbps simétrico para huéspedes.',
    createdAt: '2026-07-10T08:00:00Z',
  },
  {
    id: 'exp-6',
    title: 'Recarga Gas Balones Industriales Calderas',
    category: 'fixed',
    subcategory: 'gas',
    amount: 350000,
    vendor: 'Abastible Gas S.A.',
    expenseDate: '2026-07-20',
    status: 'paid',
    notes: 'Agua caliente sanitaria calderas.',
    createdAt: '2026-07-20T12:00:00Z',
  },
  // Gastos Variables
  {
    id: 'exp-7',
    title: 'Compra Reposición Blancas (Sábanas y Toallas)',
    category: 'variable',
    subcategory: 'mercaderia',
    amount: 420000,
    vendor: 'Textiles Sur Ltda',
    expenseDate: '2026-07-12',
    status: 'paid',
    notes: 'Sábanas 300 hilos para habitaciones matrimoniales.',
    createdAt: '2026-07-12T16:00:00Z',
  },
  {
    id: 'exp-8',
    title: 'Reparación Técnica Aire Acondicionado Suite 401',
    category: 'variable',
    subcategory: 'reparaciones',
    amount: 180000,
    vendor: 'Servicios ClimaFrío SpA',
    expenseDate: '2026-07-21',
    status: 'paid',
    notes: 'Cambio de filtro y recarga de refrigerante R410A.',
    createdAt: '2026-07-21T15:30:00Z',
  },
  {
    id: 'exp-9',
    title: 'Insumos Mercadería Cafetería y Minibar',
    category: 'variable',
    subcategory: 'mercaderia',
    amount: 650000,
    vendor: 'Distribuidora Central HORECA',
    expenseDate: '2026-07-23',
    status: 'paid',
    notes: 'Bebidas, café en grano, snacks y amenidades.',
    createdAt: '2026-07-23T10:00:00Z',
  },
];

export const INITIAL_DEBTS: Debt[] = [
  {
    id: 'debt-rec-1',
    type: 'receivable',
    entityName: 'Empresas Turísticas Sur SpA',
    rutOrPhone: '76.890.123-5',
    amount: 450000,
    description: 'Reserva corporativa 5 noches grupo técnico. Pago a 30 días.',
    dueDate: '2026-08-15',
    status: 'pending',
    createdAt: '2026-07-15',
  },
  {
    id: 'debt-rec-2',
    type: 'receivable',
    entityName: 'Carlos Mendoza (Huésped 201)',
    rutOrPhone: '14.892.310-7',
    amount: 35000,
    description: 'Saldo pendiente por servicio de minibar y estada.',
    dueDate: '2026-07-28',
    status: 'pending',
    createdAt: '2026-07-25',
  },
  {
    id: 'debt-pay-1',
    type: 'payable',
    entityName: 'Distribuidora Aseo Limpio Ltda',
    rutOrPhone: '77.123.456-9',
    amount: 280000,
    description: 'Factura F-4890 Insumos de Aseo Químico Industrial.',
    dueDate: '2026-08-05',
    status: 'pending',
    createdAt: '2026-07-20',
  },
  {
    id: 'debt-pay-2',
    type: 'payable',
    entityName: 'Proveedor Cafetería Gourmet SpA',
    rutOrPhone: '76.443.210-1',
    amount: 190000,
    description: 'Factura F-1102 Café tostado y tés de selección.',
    dueDate: '2026-08-10',
    status: 'pending',
    createdAt: '2026-07-22',
  },
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  // 1. Insumos de Aseo y Amenidades
  {
    id: 'inv-aseo-1',
    code: 'ASE-001',
    name: 'Detergente Industrial Hipoalergénico (20L)',
    category: 'aseo_amenidades',
    currentStock: 3,
    minStockThreshold: 5, // CRITICAL ALERT!
    unit: 'litros',
    unitCost: 32000,
    supplier: 'Distribuidora Aseo Limpio',
    lastRestocked: '2026-07-02',
    notes: 'Utilizado en lavandería para sábanas.',
  },
  {
    id: 'inv-aseo-2',
    code: 'ASE-002',
    name: 'Jabón Líquido Amenidad 30ml (Caja x100)',
    category: 'aseo_amenidades',
    currentStock: 4,
    minStockThreshold: 10, // CRITICAL ALERT!
    unit: 'cajas',
    unitCost: 18500,
    supplier: 'Hotel Supplies Chile',
    lastRestocked: '2026-06-20',
    notes: 'Amenidades baños habitaciones.',
  },
  {
    id: 'inv-aseo-3',
    code: 'ASE-003',
    name: 'Juegos Sábanas Algodón 300 Hilos 2 Plazas',
    category: 'aseo_amenidades',
    currentStock: 25,
    minStockThreshold: 10,
    unit: 'unidades',
    unitCost: 28000,
    supplier: 'Textiles Sur Ltda',
    lastRestocked: '2026-07-12',
  },
  {
    id: 'inv-aseo-4',
    code: 'ASE-004',
    name: 'Papel Higiénico Doble Hoja Premium (Pack 40)',
    category: 'aseo_amenidades',
    currentStock: 12,
    minStockThreshold: 15, // CRITICAL ALERT!
    unit: 'paquetes',
    unitCost: 14000,
    supplier: 'CMPC Papeles',
    lastRestocked: '2026-07-08',
  },

  // 2. Alimentos y Cafetería
  {
    id: 'inv-ali-1',
    code: 'ALI-001',
    name: 'Bebida Coca-Cola Original 350ml (Lata x24)',
    category: 'alimentos_bebidas',
    currentStock: 8,
    minStockThreshold: 20, // CRITICAL ALERT!
    unit: 'unidades',
    unitCost: 850,
    supplier: 'Andina Coca-Cola',
    lastRestocked: '2026-07-15',
    notes: 'Stock minibar y recepción.',
  },
  {
    id: 'inv-ali-2',
    code: 'ALI-002',
    name: 'Agua Mineral Vital Sin Gas 500ml',
    category: 'alimentos_bebidas',
    currentStock: 35,
    minStockThreshold: 15,
    unit: 'unidades',
    unitCost: 550,
    supplier: 'Andina Coca-Cola',
    lastRestocked: '2026-07-18',
  },
  {
    id: 'inv-ali-3',
    code: 'ALI-003',
    name: 'Café en Grano Premium Espresso (1 kg)',
    category: 'alimentos_bebidas',
    currentStock: 2,
    minStockThreshold: 4, // CRITICAL ALERT!
    unit: 'kg',
    unitCost: 19000,
    supplier: 'Cafetería Gourmet SpA',
    lastRestocked: '2026-07-01',
    notes: 'Cafetera exprés máquina desayuno.',
  },
  {
    id: 'inv-ali-4',
    code: 'ALI-004',
    name: 'Cerveza Artesanal Local 330ml (Pack x12)',
    category: 'alimentos_bebidas',
    currentStock: 24,
    minStockThreshold: 12,
    unit: 'botellas',
    unitCost: 1800,
    supplier: 'Cervecería Colonos',
    lastRestocked: '2026-07-20',
  },
  {
    id: 'inv-ali-5',
    code: 'ALI-005',
    name: 'Vino Reserva Carmenere 750ml',
    category: 'alimentos_bebidas',
    currentStock: 14,
    minStockThreshold: 6,
    unit: 'botellas',
    unitCost: 6500,
    supplier: 'Viña Colchagua',
    lastRestocked: '2026-07-10',
  },
];

export const INITIAL_PROFIT_GOAL: ProfitGoal = {
  monthlyTarget: 12000000, // $12.000.000 CLP Meta Mensual de Utilidad Neta
};
